global using Microsoft.EntityFrameworkCore;
global using Ordering.Domain.SeedWork;
global using Ordering.Domain.AggregatesModel.OrderAggregate;
global using Ordering.Domain.AggregatesModel.BuyerAggregate;
global using MediatR;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Ordering.Infrastructure.EntityConfigurations;
global using Ordering.Infrastructure.Idempotency;
global using Ordering.Domain.Exceptions;